version: "3.8"

services:
  oracle-db:
    build:
      context: ./oracle
    container_name: oracle21c-container
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - backendnet

  redis:
    image: redis:7-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backendnet

  backend:
    build:
      context: ./backend
    container_name: spring-backend
    depends_on:
      - oracle-db
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: oracle
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - backendnet
      - webnet

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    depends_on:
      - backend
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    networks:
      - webnet
volumes:
  oracle-data:
  redis-data:

networks:
  webnet:
  backendnet:
